name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          rustflags: ''
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1